# Generated by Django 5.1.1 on 2024-10-06 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('input_statement', models.TextField()),
                ('output_statement', models.TextField()),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('is_practice', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='practice.problem')),
            ],
        ),
    ]
