# Generated by Django 5.1.1 on 2024-10-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_problemtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty_level',
            field=models.CharField(default='Easy', max_length=50),
        ),
    ]
