# Generated by Django 5.1.1 on 2024-10-06 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('practice', '0003_problem_difficulty_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSubmission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('ME', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=50)),
                ('execution_time', models.IntegerField(blank=True, null=True)),
                ('memory_used', models.IntegerField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
    ]
