# Generated by Django 5.1.1 on 2024-10-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_usersolvedproblemscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSolvedProblemsCount',
        ),
    ]
