# Generated by Django 5.1.1 on 2024-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_delete_usersolvedproblemscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssubmission',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('ME', 'Memory Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error')], max_length=20),
        ),
    ]
