# Generated by Django 5.1.1 on 2024-10-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_solved_problem_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='solved_problem_count',
        ),
    ]
