# Generated by Django 5.1.1 on 2024-10-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0002_alter_contest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='problem_num',
            field=models.TextField(default='A'),
        ),
    ]
