# Generated by Django 5.1.1 on 2024-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0003_contestproblem_problem_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='problem_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='problem_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='problem_c',
            field=models.BooleanField(default=False),
        ),
    ]
