# Generated by Django 5.1.1 on 2024-10-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete', '0004_participant_problem_a_participant_problem_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='memory_used',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
